version: "3"
service:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Admin123"
      MYSQL_DATABASE: "hex_test"
    volumes:
      - ./test/testdb/:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
  grpc:
    build: .
    environment:
      DB_DRIVER: "mysql"
      DATA_SOURCE_NAME: "root:Admin123@tcp(db:3306)/hex_test"
    depends_on:
      - db
    command: ["go", "test", "-v", "./..."]
