version: "3.8"

networks:
  overlay:

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "go_hex_http"
      MYSQL_PORT: 3306
      MYSQL_USER: "go-hex-arch-http"
      MYSQL_PASSWORD: "password"
      DB_DRIVER: "mysql"
      DATA_SOURCE_NAME: "root:password@tcp(localhost:3306)/go_hex_http"
    volumes:
      - ./docker/conf/mysql.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./docker/data:/var/lib/mysql
      - ./docker/logs:/var/log/mysql
    ports:
      - "3307:3306"
    networks:
      - overlay
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
